image: Visual Studio 2017
branches:
  only:
    - develop

install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;

build_script:
  - qmake src/src.pro  -spec win32-g++ "CONFIG+=debug" "DEFINES+=MYDEFINES" && qmake_all
  - C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
  - dir
